### ISSUE TITLE
版权问题

### ISSUE THREAD

**Issue by equation314** [zhzh2001/Learning#2]
你不应该把模拟赛和讲课资料放出来

**Comment by zhzh2001** [comment]
有道理，但是这个地方并没有多少人知道，仅在内部公开。我指的版权问题是文档的协议存在冲突。

**Comment by equation314** [comment]
不太好，还是可能会被找到。真的要用 git 的话请放入私有仓库，不应完全公开。题目、数据、标程、课件都是很宝贵的资源。
